"""Morning Worker shows only leads it can work today (2026-10-02).

Drives design-preview.html (fake leads, no gate), rebuilt from the current template on every run.
Rows are cloned from the preview's own DATA and edited, so no real lead is involved.

Pins:
  - a first touch whose addresses the bridge would hold (fth) and that has no dialable phone
    leaves the worker; with a phone it moves to the call bucket, never the email bucket
  - a lead whose only phone is DNC-flagged and has no mailable address leaves the worker
  - a waiting reply stays even with nothing to send or dial
  - lane tabs count workable leads and an empty lane's tab is hidden (the open lane stays)
  - an explicit lane is honoured; no lane opens the first lane with someone workable in it
  - the 8am auto-run opens the first non-empty lane, so no earlier lane is skipped (_autoRunLane)
"""
import asyncio, os, pathlib, subprocess, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
from playwright.async_api import async_playwright

SRC = pathlib.Path(__file__).with_name('design-preview.html')
# The tracked preview is only regenerated by hand, so build it here: a stale preview tests old code.
subprocess.run([sys.executable, str(pathlib.Path(__file__).with_name('build_preview.py'))], check=True,
               stdout=subprocess.DEVNULL)
ok, bad = [], []


def rec(n, c, d=''):
    (ok if c else bad).append(n)
    print(('  PASS ' if c else '  FAIL ') + n + ((' | ' + str(d)) if d else ''))


SETUP = r"""
() => {
  const base = DATA.find(r => r && r.case) ;
  const day = n => { const t = new Date(); t.setDate(t.getDate() + n);
                     return (t.getMonth()+1) + '/' + t.getDate() + '/' + t.getFullYear(); };
  const mk = (c, o) => Object.assign(JSON.parse(JSON.stringify(base)), {
      case: c, sibclaimed: false, saleBkAct: false, lpDismissed: false, ddhold: false, vac: false,
      warn: '', st: '', lp: false, phones: [], phdnc: [], phsrc: [], emails: [], fth: undefined,
      auction: day(20), days: 20, owner: 'TEST ' + c, first: 'Test' }, o);
  DATA.length = 0;
  DATA.push(
    mk('T-EMAIL-OK',   {emails: ['ok1@gmail.com']}),
    mk('T-FTH-PHONE',  {emails: ['held2@gmail.com'], fth: 1, phones: ['3055550102']}),
    mk('T-FTH-NONE',   {emails: ['held3@gmail.com'], fth: 1}),
    mk('T-DNC-ONLY',   {phones: ['3055550104'], phdnc: [true]}),
    mk('T-JUNK-ONLY',  {emails: ['x@junkdomain-not-allowed.example']}),
    mk('T-URG-NONE',   {emails: ['held6@gmail.com'], fth: 1, auction: day(3), days: 3})
  );
  return DATA.length;
}
"""


async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path=os.environ.get('PW_CHROMIUM') or None)
        ctx = await b.new_context()
        pg = await ctx.new_page()
        errs = []
        pg.on('pageerror', lambda e: errs.append(str(e)))
        await pg.goto(SRC.as_uri())
        await pg.wait_for_timeout(2000)
        n = await pg.evaluate(SETUP)
        rec('fixture rows loaded', n == 6, n)

        reach = await pg.evaluate("() => Object.fromEntries(DATA.map(r => [r.case, _workerReach(r)]))")
        rec('mailable unheld address -> email', reach['T-EMAIL-OK'] == 'email', reach)
        rec('held first touch with a phone -> phone, not email', reach['T-FTH-PHONE'] == 'phone')
        rec('held first touch, no phone -> nothing', reach['T-FTH-NONE'] == '')
        rec('DNC-only phone, no email -> nothing', reach['T-DNC-ONLY'] == '')
        rec('junk-domain email only -> nothing', reach['T-JUNK-ONLY'] == '')

        cm = await pg.evaluate("() => { const r = DATA.find(x => x.case === 'T-FTH-PHONE'); const m = _cardMail(r); return [m.to, m.body, m.mailWhy]; }")
        rec('held first touch carries no email payload (no refused /send, straight to the phone path)',
            cm[0] == '' and cm[1] == '' and cm[2] == 'fth', cm)
        q = await pg.evaluate("() => _workerQueue('active').map(r => r.case)")
        rec('active queue holds only workable leads', set(q) == {'T-EMAIL-OK', 'T-FTH-PHONE'}, q)
        rec('email lead is queued ahead of the call-bucket lead',
            q.index('T-EMAIL-OK') < q.index('T-FTH-PHONE') if len(q) == 2 else False, q)
        wk = await pg.evaluate("() => ({u:_laneWorkable('urgent'), a:_laneWorkable('active'), e:_laneWorkable('early')})")
        rec('workable counts: urgent 0, active 2', wk['u'] == 0 and wk['a'] == 2, wk)

        # the 8am auto-run's opening lane: first lane whose queue is non-empty (urgent here holds nobody workable)
        al = await pg.evaluate("() => _autoRunLane()")
        rec('auto-run opens the first non-empty lane (ACTIVE, not empty URGENT)', al == 'active', al)
        al2 = await pg.evaluate("""() => { const keep = DATA.slice(); DATA.length = 0;
            const u = Object.assign({}, keep.find(x => x.case === 'T-FTH-PHONE'), {case:'T-URG-PHONE', auction: keep.find(x => x.case === 'T-URG-NONE').auction, days: 3});
            DATA.push(u, keep.find(x => x.case === 'T-EMAIL-OK')); const v = _autoRunLane() + ':' + _workerQueue('urgent').length;
            DATA.length = 0; keep.forEach(x => DATA.push(x)); return v; }""")
        rec('a phone-only URGENT lane is not skipped for a later email lane', al2 == 'urgent:1', al2)

        # a waiting reply survives with nothing to send or dial
        rr = await pg.evaluate("""() => { const r = DATA.find(x => x.case === 'T-FTH-NONE');
            const keep = window._replyWaiting; window._replyWaiting = x => x === r;
            const v = _workerReach(r); window._replyWaiting = keep; return v; }""")
        rec('a waiting reply stays even with no channel', rr == 'reply', rr)

        # no lane given -> first lane with someone workable (urgent is empty here)
        async with ctx.expect_page() as np:
            await pg.evaluate("() => openMorningWorker()")
        w = await np.value
        await w.wait_for_timeout(1200)
        labels = await w.locator('.mwlane .lt').all_inner_texts()
        flat = ' | '.join(x.replace('\n', ' ') for x in labels)
        on = await w.locator('.mwlane.on .lt').all_inner_texts()
        rec('no lane asked -> opens ACTIVE (urgent has nobody workable)', on and 'ACTIVE' in on[0], on)
        rec('empty URGENT tab is hidden', 'URGENT' not in flat, flat)
        rec('ACTIVE tab counts 2 workable', any('ACTIVE' in x and x.strip().endswith('2') for x in labels), flat)
        await w.close()

        # explicit lane (the 8am auto-start passes 'urgent') is honoured and its tab stays
        async with ctx.expect_page() as np:
            await pg.evaluate("() => openMorningWorker('urgent', false)")
        w = await np.value
        await w.wait_for_timeout(1200)
        on = await w.locator('.mwlane.on .lt').all_inner_texts()
        rec("explicit 'urgent' stays selected even when empty", on and 'URGENT' in on[0], on)
        body = await w.locator('#mwmain').inner_text()
        rec('empty open lane explains itself', 'Nothing to work in URGENT' in body, body[:120].replace('\n', ' '))
        await w.close()

        rec('no page errors', not errs, errs[:2])
        await b.close()
    print('\n%d passed, %d failed' % (len(ok), len(bad)))
    sys.exit(1 if bad else 0)


asyncio.run(main())
