# -*- coding: utf-8 -*-
"""Bundle everything the OTHER PC needs to run DealFlow, into one zip on the Desktop.

The repo is public, so `git clone` gets the CODE for free. What it does NOT get is everything in
.gitignore — and that is precisely the stuff that is either paid for, irreplaceable, or legally
load-bearing:

  SECRETS         8 API keys / webhook URLs. Without them: no skiptrace, no captcha, no email.
  LEDGERS         mail_sent.json + the opt-out ledger. Without them the second PC has NO memory of
                  who was already contacted or who opted out -> it will re-mail suppressed people.
                  That is the one category where a missing file is a COMPLIANCE problem, not an
                  inconvenience, so they are copied first and verified loudly.
  PAID DATA       skiptrace / whitepages / llc_officers / hardmoney enrichment. Real dollars spent.
  LIVE STATE      worker_notes.json — the call log, statuses and appointments (Amlong, Miranda...).

Run:  python prep_desktop.py
Then hand-carry the zip (USB or a PRIVATE cloud folder). Never email it, never put it in the repo:
it contains live API keys AND the personal data of people in foreclosure.
"""
import datetime
import os
import subprocess
import sys
import zipfile

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

HERE = os.path.dirname(os.path.abspath(__file__))
TODAY = datetime.date(2026, 8, 20)
DESK = os.path.expanduser(os.path.join('~', 'OneDrive', 'Desktop'))
OUT = os.path.join(DESK, 'DEALFLOW_TRANSFER_%s.zip' % TODAY.isoformat())

# files whose ABSENCE on the second PC causes a compliance failure, not just a slower run
LEDGERS = ('mail_sent.json', 'optout.json', 'opt_out.json', 'optouts.json',
           'bounces.json', 'suppression.json', 'dnc.json')
# regenerated by a single refresh — copied anyway (they are small) but never worth blocking on
CHEAP = ('leads_final.json', 'leads_raw.json', 'broward_leads.json', 'palmbeach_leads.json')

CLAUDE = os.path.expanduser(os.path.join('~', '.claude'))
MEMDIR = os.path.join(CLAUDE, 'projects', 'C--Users-olqbb-projects-obsidian-vault', 'memory')


def ignored_files():
    """Every gitignored regular file in the repo root (that is exactly 'what git will not carry')."""
    names = [f for f in os.listdir(HERE) if os.path.isfile(os.path.join(HERE, f))]
    if not names:
        return []
    r = subprocess.run(['git', 'check-ignore'] + names, cwd=HERE,
                       capture_output=True, text=True)
    out = [f.strip().strip('"') for f in r.stdout.split('\n') if f.strip()]
    keep = []
    for f in out:
        if f.endswith(('.log', '.bin', '.png', '.pdf', '.html')):
            continue                       # logs + my scratch renders + client artifacts
        if f.startswith(('_probe_', '_sat', '_amlong')):
            continue
        keep.append(f)
    return sorted(keep)


def main():
    files = ignored_files()
    secrets = [f for f in files if f.endswith(('.key', '.url'))]
    ledgers = [f for f in files if f in LEDGERS]
    data = [f for f in files if f not in secrets and f not in ledgers]

    os.makedirs(DESK, exist_ok=True)
    n = 0
    with zipfile.ZipFile(OUT, 'w', zipfile.ZIP_DEFLATED) as z:
        for f in secrets:
            z.write(os.path.join(HERE, f), 'secrets/' + f); n += 1
        for f in ledgers:
            z.write(os.path.join(HERE, f), 'ledgers/' + f); n += 1
        for f in data:
            z.write(os.path.join(HERE, f), 'data/' + f); n += 1
        # Claude Code brain: global instructions + the 117-file memory
        for f in ('CLAUDE.md', 'agents.md', 'quality-framework.md', 'alejandro-context.md',
                  'settings.json'):
            p = os.path.join(CLAUDE, f)
            if os.path.exists(p):
                z.write(p, 'claude/' + f); n += 1
        if os.path.isdir(MEMDIR):
            for f in sorted(os.listdir(MEMDIR)):
                if f.endswith('.md'):
                    z.write(os.path.join(MEMDIR, f), 'claude/memory/' + f); n += 1
        # scheduled tasks: the exported XMLs carry hardening (PT6H limit, battery/wake settings)
        # that must not be retyped from memory, plus the installer that repoints and re-principals
        # them. Kept OUT of git (they embed this machine's SID) so they travel only in this bundle.
        tdir = os.path.join(HERE, 'desktop-setup')
        for root, _dirs, fs in os.walk(tdir):
            for f in fs:
                p = os.path.join(root, f)
                z.write(p, 'desktop-setup/' + os.path.relpath(p, tdir).replace('\\', '/')); n += 1
        # DealflowSendServerDaily launches this from the Startup folder — it lives OUTSIDE the repo,
        # so a git clone alone leaves that task pointing at a file that is not there.
        vbs = os.path.expanduser(os.path.join(
            '~', 'AppData', 'Roaming', 'Microsoft', 'Windows', 'Start Menu', 'Programs',
            'Startup', 'DealflowSendServer.vbs'))
        if os.path.exists(vbs):
            z.write(vbs, 'startup/DealflowSendServer.vbs'); n += 1

    print('WROTE %s' % OUT)
    print('  %.1f MB, %d files' % (os.path.getsize(OUT) / 1048576, n))
    print()
    print('  secrets/  %2d  %s' % (len(secrets), ', '.join(secrets)))
    print('  ledgers/  %2d  %s' % (len(ledgers), ', '.join(ledgers) or '(none matched — CHECK)'))
    print('  data/     %2d  files' % len(data))
    print('  claude/       CLAUDE.md + agents + quality-framework + %d memory files'
          % (len(os.listdir(MEMDIR)) if os.path.isdir(MEMDIR) else 0))
    print('  desktop-setup/  8 exported task XMLs + install-tasks.ps1')
    print('  startup/        DealflowSendServer.vbs (lives outside the repo)')
    print()
    if not ledgers:
        print('  !! NO LEDGER FILE MATCHED. Do not run outreach on the second PC until you')
        print('     confirm how mail_sent / opt-outs travel, or it can re-mail suppressed people.')
    print('  Contains LIVE API KEYS and homeowner PII. USB or private cloud only — never email,')
    print('  never commit.')


if __name__ == '__main__':
    main()
